Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -146,16 +146,39 @@ jobs:
       contents: write
 
     runs-on: ubuntu-latest
+    env:
+      artifacts-root: artifacts
+      assets-root: assets
 
     steps:
     - name: Download All Artifacts
       uses: actions/download-artifact@v4
       with:
-        path: artifacts
+        path: "${{ env.artifacts-root }}"
+
+    - name: Prepare Assets
+      shell: bash
+      run: |
+
+        asset_root="${{ env.assets-root }}"
+        artifact_pattern="${{ env.artifacts-root }}/*"
+        
+        mkdir "assets"
+        for item in $artifact_pattern ; do
+          if [ -d "$item" ] ; then
+            item_name="${item##*/}"
+
+            # remove version
+            asset_name="${item_name% [*}.zip"
+            
+            zip -r -j "$asset_root/$asset_name" "$item" && echo "Archiving of the asset '$asset_name' has been completed successfully." || echo "::warning::Failed to archive asset '$asset_name'"
+          fi
+        done
+
 
     - name: Upload All Assets
-      uses: finebits/github-actions/upload-release-asset@v1
+      uses: al-kau/finebits-github-actions/upload-release-asset@ac311f4d3e0a03220e22b63378f3ef0a006a5805 
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ github.event.release.tag_name }}
-        path: "artifacts/*"
+        path: "${{ env.assets-root }}/*"
